Update for versioningit and stuff
Becksteinlab/propkatraj pull request #65
Opened 2023-11-09 20:11 UTC by IAlibay

2023-11-09 20:11 UTC, IAlibay commented
CI  hasn't been running for a long while, let's see what happens...

2023-11-10 21:06 UTC, orbeckst commented
Thanks for starting the work.

For reference I am copying the current failures from setuptools:
```
[WARNING ] versioningit: Version extracted from tag 'release-2.0.0' is not PEP 440-compliant
      [ERROR   ] versioningit: InvalidVersionError: Cannot parse version 'release-2.0.0'
      error: Multiple top-level packages discovered in a flat-layout: ['devtools', 'propkatraj'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
```

1. need to change how we tag to make versioningit happy
2. need to fix something related to the package layout

2023-11-10 21:08 UTC, orbeckst commented on pyproject.toml
> +match = ["release-*"]
I am now surprised that versioningit failed, given that it should have found the tag. Maybe not PEP440 compliant?

2023-11-10 21:09 UTC, orbeckst commented on setup.py
hooray!

2023-11-10 21:09 UTC, orbeckst commented on setup.py
setup.py gone!

2023-11-19 18:27 UTC, IAlibay commented
@orbeckst I think this is good to go?

2023-11-19 22:50 UTC, orbeckst requested changes
Many thanks. There are two empty offset lock files checked in. Should they be included?

2023-11-19 22:50 UTC, orbeckst commented on propkatraj/tests/data/.atterr_frame1.xtc_offsets.lock
Should this be really included?

2023-11-19 22:50 UTC, orbeckst commented on propkatraj/tests/data/.indexerr_frame14.xtc_offsets.lock
Should this included?

2023-11-19 23:23 UTC, IAlibay commented on propkatraj/tests/data/.atterr_frame1.xtc_offsets.lock
uh oh, looks like something went wrong with the gitignore!

2023-12-23 15:51 UTC, IAlibay commented
This should be good to go for now @orbeckst - next up let's aim for the latest propka release!

2023-12-23 17:01 UTC, orbeckst approved these changes

2023-12-23 17:01 UTC, orbeckst commented
Cheers and yes!

2023-12-23 21:23 UTC, merged